# Generated by Django 5.0.7 on 2024-07-22 15:59

import Customusers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', Customusers.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
