# Generated by Django 5.0.7 on 2024-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customusers', '0007_users_is_verified_users_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
