# Generated by Django 5.0.7 on 2024-08-02 17:08

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('show_on_home', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categoryImages/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('product_code', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('after_discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('discription', models.TextField(max_length=10000)),
                ('ratting', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=1000)),
                ('stock', models.IntegerField()),
                ('total_review', models.IntegerField()),
                ('in_stock', models.BooleanField(default=False)),
                ('buying_price', models.IntegerField(blank=True, null=True)),
                ('product_discription', product.models.MyFroalaField(blank=True, null=True)),
                ('product_tutorial', product.models.MyFroalaField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='product.category')),
                ('sub_category', models.ManyToManyField(blank=True, null=True, to='product.sub_category')),
            ],
        ),
    ]
