# Generated by Django 5.0.7 on 2024-08-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_photo_products_image_productmedia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
