# Generated by Django 5.0.7 on 2024-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_category_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='')),
                ('shop_poster', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('linkdin', models.CharField(max_length=200)),
                ('twiter', models.CharField(max_length=200)),
                ('instragram', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('poster', models.ImageField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
                ('poster', models.ImageField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={},
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='slug',
        ),
        migrations.AddField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='SubCategoryImage/'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
