# Generated by Django 5.0.7 on 2024-08-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_homepage_homeslide_specialoffer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
