# Generated by Django 5.0.7 on 2024-09-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_delete_homepage_delete_homeslide_delete_specialoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
